name: flutter_smart_watch_platform_interface
description: A common platform interface for the flutter_smart_watch plugin.
version: 0.0.2
homepage: https://github.com/ssttonn/flutter_smart_watch/tree/master/flutter_smart_watch_platform_interface

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
